### ISSUE TITLE
contribution to NWChem overview paper

### ISSUE THREAD

**Issue by edoapra** [Konjkov/molden2qmc#11]
@Konjkov Vladimir, I am trying to contact you since I would like to ask you if you are willing to be an author to an upcoming article about NWChem. Is this the right way to contact you? Thanks
Edoardo Apra

**Comment by Konjkov** [comment]
Dear Edoardo.
I apologize for missing your letter, it seemed to me that I answered, but yes this is also a good place to contact me. I would like to know more about the content of the article and what should be my contribution to. You can answer me by Konjkov.VV@gmail.com or here.

**Comment by edoapra** [comment]
Dear Vladimir
Could you please mail me your current affiliation?
Thanks
